name: macos_clang
# CERN ROOT requires minimum cxx_standard: 17 --> cxx_standard: 14 only tested for core library
# CERN ROOT has to be compiled in a compatible version with regard to gcc/clang and cxx_standard
# For Qt the compiler and cxx_standard do not matter that much

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-14]
        qt_version: [5, 6]
        compiler: [msvc]
        cpp_standard: [17, 20]
        
    name: eudaq_full_build-${{matrix.os}}-${{matrix.compiler}}-cxx_standard-${{matrix.cpp_standard}}-qt-${{matrix.qt_version}}

    steps:
    - uses: actions/checkout@v4
             
    - name: build CERN ROOT
      id: root_build
      run: |
        export CERN_ROOT_DOWNLOAD_NAME=root_v6.32.02.source.tar.gz
        wget -nv https://root.cern/download/$CERN_ROOT_DOWNLOAD_NAME
        mkdir root_source
        tar -xzf $CERN_ROOT_DOWNLOAD_NAME -C ./root_source --strip-components=1
        rm -f $CERN_ROOT_DOWNLOAD_NAME
        mkdir -p ~/eudaq_dependencies/root/
        mkdir root_build
        cd root_build
        echo "C++ compiler used: ${{ steps.install_cc.outputs.cxx }}"
        echo "C compiler used: ${{ steps.install_cc.outputs.cc }}"
        cmake -D CMAKE_CXX_COMPILER=${{ steps.install_cc.outputs.cxx }} -D CMAKE_C_COMPILER=${{ steps.install_cc.outputs.cc }} -DCMAKE_INSTALL_PREFIX=~/eudaq_dependencies/root/ -Dclad=OFF -Dxrootd=OFF -DCMAKE_CXX_STANDARD=${{matrix.cpp_standard}} ../root_source/
        make -j12 install
        cd ..
        rm -rf root_source
        rm -rf root_build

       
    - name: Configure CMake
      # Configure CMake in a 'build' subdirectory. `CMAKE_BUILD_TYPE` is only required if you are using a single-configuration generator such as make.
      # See https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html?highlight=cmake_build_type
      run: |
#        sudo mkdir -p /opt/local/lib
#        sudo ln -s /opt/homebrew/lib /opt/local/lib
        source ~/eudaq_dependencies/root/bin/thisroot.sh
        cmake -D EUDAQ_BUILD_STDEVENT_MONITOR=ON -D EUDAQ_BUILD_GUI=ON -D USER_BUILD_TLU_ONLY_CONVERTER=ON -D USER_EUDET_BUILD=ON -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      # Build your program with the given configuration
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Test
      working-directory: ${{github.workspace}}/build
      # Execute tests defined by the CMake configuration.  
      # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
      run: ctest -C ${{env.BUILD_TYPE}}
      
